/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'name' : string,
  'preferences' : string,
  'contactDetails' : string,
}
export interface Invoice {
  'customerName' : string,
  'timestamp' : Time,
  'paymentMode' : string,
  'totalPrice' : bigint,
  'itemsOrdered' : Array<[string, bigint]>,
}
export type Recipe = Array<[string, bigint]>;
export interface SaladBowl {
  'active' : boolean,
  'name' : string,
  'price' : bigint,
  'bowlType' : SaladBowlType,
  'recipe' : Recipe,
}
export type SaladBowlType = { 'custom' : null } |
  { 'gm250' : null } |
  { 'gm350' : null } |
  { 'gm500' : null };
export interface Subscription {
  'id' : bigint,
  'customerName' : string,
  'endDate' : Time,
  'name' : string,
  'remainingDeliveries' : bigint,
  'isPaid' : boolean,
  'phoneNumber' : string,
  'price' : bigint,
  'planType' : string,
  'bowlSize' : SaladBowlType,
  'startDate' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addCustomer' : ActorMethod<[bigint, string, string, string], boolean>,
  'addProduct' : ActorMethod<[SaladBowl], bigint>,
  'bowlSizes' : ActorMethod<
    [],
    { 'gm250' : boolean, 'gm350' : boolean, 'gm500' : boolean }
  >,
  'createSubscription' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      SaladBowlType,
      bigint,
      boolean,
      Time,
      Time,
      bigint,
    ],
    boolean
  >,
  'deductIngredientsOnSale' : ActorMethod<[Invoice], undefined>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteSubscription' : ActorMethod<[bigint], boolean>,
  'editSaladBowlRecipe' : ActorMethod<[string, Recipe], boolean>,
  'editSubscription' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      SaladBowlType,
      bigint,
      boolean,
      Time,
      Time,
      bigint,
    ],
    boolean
  >,
  'getAllActiveProducts' : ActorMethod<[], Array<SaladBowl>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllProductsWithInactive' : ActorMethod<[], Array<SaladBowl>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAnalyticsMetrics' : ActorMethod<
    [],
    {
      'monthlySales' : bigint,
      'dailySales' : bigint,
      'weeklySales' : bigint,
      'cashFlow' : bigint,
      'dailyExpenses' : bigint,
    }
  >,
  'getProduct' : ActorMethod<[bigint], [] | [SaladBowl]>,
  'monthlyPlanDuration' : ActorMethod<[], bigint>,
  'toggleSaladBowlAvailability' : ActorMethod<[string, boolean], undefined>,
  'updateProduct' : ActorMethod<[bigint, SaladBowl], boolean>,
  'weeklyPlanDuration' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];