/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ingredient = IDL.Record({
  'unitType' : IDL.Text,
  'lowStockThreshold' : IDL.Nat,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'costPricePerUnit' : IDL.Nat,
});
export const SaladBowlType = IDL.Variant({
  'custom' : IDL.Null,
  'gm250' : IDL.Null,
  'gm350' : IDL.Null,
  'gm500' : IDL.Null,
});
export const Recipe = IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat));
export const SaladBowl = IDL.Record({
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'price' : IDL.Nat,
  'bowlType' : SaladBowlType,
  'recipe' : Recipe,
});
export const Time = IDL.Int;
export const Invoice = IDL.Record({
  'customerName' : IDL.Text,
  'timestamp' : Time,
  'paymentMode' : IDL.Text,
  'totalPrice' : IDL.Nat,
  'itemsOrdered' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferences' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const StockTransactionType = IDL.Variant({
  'writeOff' : IDL.Null,
  'stockOut' : IDL.Null,
  'stockIn' : IDL.Null,
});
export const StockTransaction = IDL.Record({
  'unitType' : IDL.Text,
  'transactionType' : StockTransactionType,
  'supplier' : IDL.Opt(IDL.Text),
  'date' : Time,
  'quantity' : IDL.Nat,
  'ingredientName' : IDL.Text,
  'costPrice' : IDL.Opt(IDL.Nat),
  'transactionId' : IDL.Nat,
  'reason' : IDL.Text,
});
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'endDate' : Time,
  'name' : IDL.Text,
  'remainingDeliveries' : IDL.Int,
  'isPaid' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Nat,
  'planType' : IDL.Text,
  'bowlSize' : SaladBowlType,
  'startDate' : Time,
});
export const InventoryItem = IDL.Record({
  'unitType' : IDL.Text,
  'quantityInStock' : IDL.Nat,
  'ingredientName' : IDL.Text,
});
export const StockStatus = IDL.Record({
  'unitType' : IDL.Text,
  'quantityInStock' : IDL.Nat,
  'isLowStock' : IDL.Bool,
  'currentQuantity' : IDL.Nat,
  'ingredientName' : IDL.Text,
  'costPricePerUnit' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'addIngredient' : IDL.Func([Ingredient], [], []),
  'addProduct' : IDL.Func([SaladBowl], [IDL.Nat], []),
  'bowlSizes' : IDL.Func(
      [],
      [
        IDL.Record({
          'gm250' : IDL.Bool,
          'gm350' : IDL.Bool,
          'gm500' : IDL.Bool,
        }),
      ],
      [],
    ),
  'createSubscription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        SaladBowlType,
        IDL.Nat,
        IDL.Bool,
        Time,
        Time,
        IDL.Int,
      ],
      [IDL.Bool],
      [],
    ),
  'deductIngredientsOnSale' : IDL.Func([Invoice], [], []),
  'deleteIngredient' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSubscription' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'editSaladBowlRecipe' : IDL.Func([IDL.Text, Recipe], [IDL.Bool], []),
  'editSubscription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        SaladBowlType,
        IDL.Nat,
        IDL.Bool,
        Time,
        Time,
        IDL.Int,
      ],
      [IDL.Bool],
      [],
    ),
  'getAllActiveProducts' : IDL.Func([], [IDL.Vec(SaladBowl)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getAllProductsWithInactive' : IDL.Func([], [IDL.Vec(SaladBowl)], ['query']),
  'getAllStockTransactions' : IDL.Func([], [IDL.Vec(StockTransaction)], []),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getAnalyticsMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'monthlySales' : IDL.Nat,
          'dailySales' : IDL.Nat,
          'weeklySales' : IDL.Nat,
          'cashFlow' : IDL.Nat,
          'dailyExpenses' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(Ingredient)], ['query']),
  'getInventoryStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalValue' : IDL.Nat,
          'items' : IDL.Vec(InventoryItem),
        }),
      ],
      [],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(SaladBowl)], ['query']),
  'getStockStatus' : IDL.Func([], [IDL.Vec(StockStatus)], []),
  'getStockTransactionsByType' : IDL.Func(
      [StockTransactionType],
      [IDL.Vec(StockTransaction)],
      [],
    ),
  'monthlyPlanDuration' : IDL.Func([], [IDL.Nat], []),
  'recordStockIn' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'recordStockOut' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'recordWriteOff' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'toggleSaladBowlAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateIngredient' : IDL.Func([IDL.Text, Ingredient], [IDL.Bool], []),
  'updateProduct' : IDL.Func([IDL.Nat, SaladBowl], [IDL.Bool], []),
  'weeklyPlanDuration' : IDL.Func([], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ingredient = IDL.Record({
    'unitType' : IDL.Text,
    'lowStockThreshold' : IDL.Nat,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'costPricePerUnit' : IDL.Nat,
  });
  const SaladBowlType = IDL.Variant({
    'custom' : IDL.Null,
    'gm250' : IDL.Null,
    'gm350' : IDL.Null,
    'gm500' : IDL.Null,
  });
  const Recipe = IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat));
  const SaladBowl = IDL.Record({
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'price' : IDL.Nat,
    'bowlType' : SaladBowlType,
    'recipe' : Recipe,
  });
  const Time = IDL.Int;
  const Invoice = IDL.Record({
    'customerName' : IDL.Text,
    'timestamp' : Time,
    'paymentMode' : IDL.Text,
    'totalPrice' : IDL.Nat,
    'itemsOrdered' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferences' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StockTransactionType = IDL.Variant({
    'writeOff' : IDL.Null,
    'stockOut' : IDL.Null,
    'stockIn' : IDL.Null,
  });
  const StockTransaction = IDL.Record({
    'unitType' : IDL.Text,
    'transactionType' : StockTransactionType,
    'supplier' : IDL.Opt(IDL.Text),
    'date' : Time,
    'quantity' : IDL.Nat,
    'ingredientName' : IDL.Text,
    'costPrice' : IDL.Opt(IDL.Nat),
    'transactionId' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'endDate' : Time,
    'name' : IDL.Text,
    'remainingDeliveries' : IDL.Int,
    'isPaid' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Nat,
    'planType' : IDL.Text,
    'bowlSize' : SaladBowlType,
    'startDate' : Time,
  });
  const InventoryItem = IDL.Record({
    'unitType' : IDL.Text,
    'quantityInStock' : IDL.Nat,
    'ingredientName' : IDL.Text,
  });
  const StockStatus = IDL.Record({
    'unitType' : IDL.Text,
    'quantityInStock' : IDL.Nat,
    'isLowStock' : IDL.Bool,
    'currentQuantity' : IDL.Nat,
    'ingredientName' : IDL.Text,
    'costPricePerUnit' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'addIngredient' : IDL.Func([Ingredient], [], []),
    'addProduct' : IDL.Func([SaladBowl], [IDL.Nat], []),
    'bowlSizes' : IDL.Func(
        [],
        [
          IDL.Record({
            'gm250' : IDL.Bool,
            'gm350' : IDL.Bool,
            'gm500' : IDL.Bool,
          }),
        ],
        [],
      ),
    'createSubscription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          SaladBowlType,
          IDL.Nat,
          IDL.Bool,
          Time,
          Time,
          IDL.Int,
        ],
        [IDL.Bool],
        [],
      ),
    'deductIngredientsOnSale' : IDL.Func([Invoice], [], []),
    'deleteIngredient' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSubscription' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'editSaladBowlRecipe' : IDL.Func([IDL.Text, Recipe], [IDL.Bool], []),
    'editSubscription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          SaladBowlType,
          IDL.Nat,
          IDL.Bool,
          Time,
          Time,
          IDL.Int,
        ],
        [IDL.Bool],
        [],
      ),
    'getAllActiveProducts' : IDL.Func([], [IDL.Vec(SaladBowl)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getAllProductsWithInactive' : IDL.Func(
        [],
        [IDL.Vec(SaladBowl)],
        ['query'],
      ),
    'getAllStockTransactions' : IDL.Func([], [IDL.Vec(StockTransaction)], []),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getAnalyticsMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'monthlySales' : IDL.Nat,
            'dailySales' : IDL.Nat,
            'weeklySales' : IDL.Nat,
            'cashFlow' : IDL.Nat,
            'dailyExpenses' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getIngredient' : IDL.Func([IDL.Text], [IDL.Opt(Ingredient)], ['query']),
    'getInventoryStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalValue' : IDL.Nat,
            'items' : IDL.Vec(InventoryItem),
          }),
        ],
        [],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(SaladBowl)], ['query']),
    'getStockStatus' : IDL.Func([], [IDL.Vec(StockStatus)], []),
    'getStockTransactionsByType' : IDL.Func(
        [StockTransactionType],
        [IDL.Vec(StockTransaction)],
        [],
      ),
    'monthlyPlanDuration' : IDL.Func([], [IDL.Nat], []),
    'recordStockIn' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'recordStockOut' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'recordWriteOff' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
    'toggleSaladBowlAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateIngredient' : IDL.Func([IDL.Text, Ingredient], [IDL.Bool], []),
    'updateProduct' : IDL.Func([IDL.Nat, SaladBowl], [IDL.Bool], []),
    'weeklyPlanDuration' : IDL.Func([], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };