/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'age' : bigint,
  'heightCm' : number,
  'name' : string,
  'email' : string,
  'preferences' : string,
  'weightKg' : number,
  'address' : string,
  'gender' : string,
  'calculatedBMI' : number,
  'phone' : string,
}
export interface Ingredient {
  'unitType' : string,
  'lowStockThreshold' : bigint,
  'supplierName' : string,
  'name' : string,
  'quantity' : bigint,
  'costPricePerUnit' : bigint,
}
export interface InventoryItem {
  'unitType' : string,
  'quantityInStock' : bigint,
  'ingredientName' : string,
}
export interface Invoice {
  'customerName' : string,
  'timestamp' : Time,
  'paymentMode' : string,
  'totalPrice' : bigint,
  'itemsOrdered' : Array<[string, bigint]>,
}
export interface Order {
  'customerName' : string,
  'deliveryAddress' : string,
  'orderStatus' : string,
  'orderTotal' : bigint,
  'orderDate' : Time,
  'orderId' : bigint,
  'paymentMode' : string,
  'customerId' : bigint,
  'phone' : string,
  'items' : Array<[string, bigint]>,
}
export type Recipe = Array<[string, bigint]>;
export interface SaladBowl {
  'active' : boolean,
  'name' : string,
  'price' : bigint,
  'bowlType' : SaladBowlType,
  'recipe' : Recipe,
}
export type SaladBowlType = { 'custom' : null } |
  { 'gm250' : null } |
  { 'gm350' : null } |
  { 'gm500' : null };
export interface StockStatus {
  'unitType' : string,
  'quantityInStock' : bigint,
  'isLowStock' : boolean,
  'currentQuantity' : bigint,
  'ingredientName' : string,
  'costPricePerUnit' : bigint,
}
export interface StockTransaction {
  'unitType' : string,
  'transactionType' : StockTransactionType,
  'supplier' : [] | [string],
  'date' : Time,
  'quantity' : bigint,
  'ingredientName' : string,
  'costPrice' : [] | [bigint],
  'transactionId' : bigint,
  'reason' : string,
}
export type StockTransactionType = { 'writeOff' : null } |
  { 'stockOut' : null } |
  { 'stockIn' : null };
export interface Subscription {
  'id' : bigint,
  'customerName' : string,
  'endDate' : Time,
  'name' : string,
  'remainingDeliveries' : bigint,
  'isPaid' : boolean,
  'phoneNumber' : string,
  'price' : bigint,
  'planType' : string,
  'bowlSize' : SaladBowlType,
  'startDate' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'heightCm' : number,
  'name' : string,
  'email' : string,
  'preferences' : string,
  'weightKg' : number,
  'address' : string,
  'gender' : string,
  'calculatedBMI' : number,
  'customerId' : bigint,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      number,
      number,
      number,
    ],
    bigint
  >,
  'addIngredient' : ActorMethod<[Ingredient], undefined>,
  'addOrder' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<[string, bigint]>,
      bigint,
      string,
      string,
    ],
    bigint
  >,
  'addProduct' : ActorMethod<[SaladBowl], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bowlSizes' : ActorMethod<
    [],
    { 'gm250' : boolean, 'gm350' : boolean, 'gm500' : boolean }
  >,
  'createSubscription' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      SaladBowlType,
      bigint,
      boolean,
      Time,
      Time,
      bigint,
    ],
    boolean
  >,
  'deductIngredientsOnSale' : ActorMethod<[Invoice], undefined>,
  'deleteIngredient' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'deleteSubscription' : ActorMethod<[bigint], boolean>,
  'editSaladBowlRecipe' : ActorMethod<[string, Recipe], boolean>,
  'editSubscription' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      SaladBowlType,
      bigint,
      boolean,
      Time,
      Time,
      bigint,
    ],
    boolean
  >,
  'getAllActiveProducts' : ActorMethod<[], Array<SaladBowl>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProductsWithInactive' : ActorMethod<[], Array<SaladBowl>>,
  'getAllStockTransactions' : ActorMethod<[], Array<StockTransaction>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAnalyticsMetrics' : ActorMethod<
    [],
    {
      'monthlySales' : bigint,
      'dailySales' : bigint,
      'weeklySales' : bigint,
      'cashFlow' : bigint,
      'dailyExpenses' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[bigint], Array<Order>>,
  'getCustomerProfile' : ActorMethod<[bigint], [] | [Customer]>,
  'getIngredient' : ActorMethod<[string], [] | [Ingredient]>,
  'getInventoryStatus' : ActorMethod<
    [],
    { 'totalValue' : bigint, 'items' : Array<InventoryItem> }
  >,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [SaladBowl]>,
  'getStockStatus' : ActorMethod<[], Array<StockStatus>>,
  'getStockTransactionsByType' : ActorMethod<
    [StockTransactionType],
    Array<StockTransaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'monthlyPlanDuration' : ActorMethod<[], bigint>,
  'recordStockIn' : ActorMethod<
    [string, bigint, string, bigint, string],
    boolean
  >,
  'recordStockOut' : ActorMethod<[string, bigint, string], boolean>,
  'recordWriteOff' : ActorMethod<[string, bigint, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleSaladBowlAvailability' : ActorMethod<[string, boolean], undefined>,
  'updateIngredient' : ActorMethod<[string, Ingredient], boolean>,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateProduct' : ActorMethod<[bigint, SaladBowl], boolean>,
  'weeklyPlanDuration' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];