/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Subscription {
    id: bigint;
    customerName: string;
    endDate: Time;
    name: string;
    remainingDeliveries: bigint;
    isPaid: boolean;
    phoneNumber: string;
    price: bigint;
    planType: string;
    bowlSize: SaladBowlType;
    startDate: Time;
}
export type Time = bigint;
export interface SaladBowl {
    active: boolean;
    name: string;
    price: bigint;
    bowlType: SaladBowlType;
    recipe: Recipe;
}
export type Recipe = Array<[string, bigint]>;
export interface Customer {
    id: bigint;
    name: string;
    preferences: string;
    contactDetails: string;
}
export interface Invoice {
    customerName: string;
    timestamp: Time;
    paymentMode: string;
    totalPrice: bigint;
    itemsOrdered: Array<[string, bigint]>;
}
export enum SaladBowlType {
    custom = "custom",
    gm250 = "gm250",
    gm350 = "gm350",
    gm500 = "gm500"
}
export interface backendInterface {
    addCustomer(id: bigint, name: string, contactDetails: string, preferences: string): Promise<boolean>;
    addProduct(product: SaladBowl): Promise<bigint>;
    bowlSizes(): Promise<{
        gm250: boolean;
        gm350: boolean;
        gm500: boolean;
    }>;
    createSubscription(id: bigint, name: string, customerName: string, phoneNumber: string, planType: string, bowlSize: SaladBowlType, price: bigint, isPaid: boolean, startDate: Time, endDate: Time, remainingDeliveries: bigint): Promise<boolean>;
    deductIngredientsOnSale(invoice: Invoice): Promise<void>;
    deleteProduct(id: bigint): Promise<boolean>;
    deleteSubscription(id: bigint): Promise<boolean>;
    editSaladBowlRecipe(bowlName: string, newRecipe: Recipe): Promise<boolean>;
    editSubscription(id: bigint, updatedName: string, updatedCustomerName: string, updatedPhoneNumber: string, updatedPlanType: string, updatedBowlSize: SaladBowlType, updatedPrice: bigint, updatedIsPaid: boolean, updatedStartDate: Time, updatedEndDate: Time, updatedRemainingDeliveries: bigint): Promise<boolean>;
    getAllActiveProducts(): Promise<Array<SaladBowl>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllProductsWithInactive(): Promise<Array<SaladBowl>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAnalyticsMetrics(): Promise<{
        monthlySales: bigint;
        dailySales: bigint;
        weeklySales: bigint;
        cashFlow: bigint;
        dailyExpenses: bigint;
    }>;
    getProduct(id: bigint): Promise<SaladBowl | null>;
    monthlyPlanDuration(): Promise<bigint>;
    toggleSaladBowlAvailability(bowlName: string, isAvailable: boolean): Promise<void>;
    updateProduct(id: bigint, updatedProduct: SaladBowl): Promise<boolean>;
    weeklyPlanDuration(): Promise<bigint>;
}
import type { Recipe as _Recipe, SaladBowl as _SaladBowl, SaladBowlType as _SaladBowlType, Subscription as _Subscription, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addProduct(arg0: SaladBowl): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_SaladBowl_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_SaladBowl_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async bowlSizes(): Promise<{
        gm250: boolean;
        gm350: boolean;
        gm500: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bowlSizes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bowlSizes();
            return result;
        }
    }
    async createSubscription(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: SaladBowlType, arg6: bigint, arg7: boolean, arg8: Time, arg9: Time, arg10: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(arg0, arg1, arg2, arg3, arg4, to_candid_SaladBowlType_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(arg0, arg1, arg2, arg3, arg4, to_candid_SaladBowlType_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async deductIngredientsOnSale(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deductIngredientsOnSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductIngredientsOnSale(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteSubscription(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubscription(arg0);
            return result;
        }
    }
    async editSaladBowlRecipe(arg0: string, arg1: Recipe): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editSaladBowlRecipe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSaladBowlRecipe(arg0, arg1);
            return result;
        }
    }
    async editSubscription(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: SaladBowlType, arg6: bigint, arg7: boolean, arg8: Time, arg9: Time, arg10: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editSubscription(arg0, arg1, arg2, arg3, arg4, to_candid_SaladBowlType_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editSubscription(arg0, arg1, arg2, arg3, arg4, to_candid_SaladBowlType_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async getAllActiveProducts(): Promise<Array<SaladBowl>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveProducts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveProducts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllProductsWithInactive(): Promise<Array<SaladBowl>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductsWithInactive();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductsWithInactive();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsMetrics(): Promise<{
        monthlySales: bigint;
        dailySales: bigint;
        weeklySales: bigint;
        cashFlow: bigint;
        dailyExpenses: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsMetrics();
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<SaladBowl | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async monthlyPlanDuration(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.monthlyPlanDuration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.monthlyPlanDuration();
            return result;
        }
    }
    async toggleSaladBowlAvailability(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSaladBowlAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSaladBowlAvailability(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: SaladBowl): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_SaladBowl_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_SaladBowl_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async weeklyPlanDuration(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.weeklyPlanDuration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.weeklyPlanDuration();
            return result;
        }
    }
}
function from_candid_SaladBowlType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaladBowlType): SaladBowlType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SaladBowl_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaladBowl): SaladBowl {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SaladBowl]): SaladBowl | null {
    return value.length === 0 ? null : from_candid_SaladBowl_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    endDate: _Time;
    name: string;
    remainingDeliveries: bigint;
    isPaid: boolean;
    phoneNumber: string;
    price: bigint;
    planType: string;
    bowlSize: _SaladBowlType;
    startDate: _Time;
}): {
    id: bigint;
    customerName: string;
    endDate: Time;
    name: string;
    remainingDeliveries: bigint;
    isPaid: boolean;
    phoneNumber: string;
    price: bigint;
    planType: string;
    bowlSize: SaladBowlType;
    startDate: Time;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        endDate: value.endDate,
        name: value.name,
        remainingDeliveries: value.remainingDeliveries,
        isPaid: value.isPaid,
        phoneNumber: value.phoneNumber,
        price: value.price,
        planType: value.planType,
        bowlSize: from_candid_SaladBowlType_n8(_uploadFile, _downloadFile, value.bowlSize),
        startDate: value.startDate
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    name: string;
    price: bigint;
    bowlType: _SaladBowlType;
    recipe: _Recipe;
}): {
    active: boolean;
    name: string;
    price: bigint;
    bowlType: SaladBowlType;
    recipe: Recipe;
} {
    return {
        active: value.active,
        name: value.name,
        price: value.price,
        bowlType: from_candid_SaladBowlType_n8(_uploadFile, _downloadFile, value.bowlType),
        recipe: value.recipe
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    gm250: null;
} | {
    gm350: null;
} | {
    gm500: null;
}): SaladBowlType {
    return "custom" in value ? SaladBowlType.custom : "gm250" in value ? SaladBowlType.gm250 : "gm350" in value ? SaladBowlType.gm350 : "gm500" in value ? SaladBowlType.gm500 : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SaladBowl>): Array<SaladBowl> {
    return value.map((x)=>from_candid_SaladBowl_n6(_uploadFile, _downloadFile, x));
}
function to_candid_SaladBowlType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaladBowlType): _SaladBowlType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SaladBowl_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaladBowl): _SaladBowl {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    name: string;
    price: bigint;
    bowlType: SaladBowlType;
    recipe: Recipe;
}): {
    active: boolean;
    name: string;
    price: bigint;
    bowlType: _SaladBowlType;
    recipe: _Recipe;
} {
    return {
        active: value.active,
        name: value.name,
        price: value.price,
        bowlType: to_candid_SaladBowlType_n3(_uploadFile, _downloadFile, value.bowlType),
        recipe: value.recipe
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaladBowlType): {
    custom: null;
} | {
    gm250: null;
} | {
    gm350: null;
} | {
    gm500: null;
} {
    return value == SaladBowlType.custom ? {
        custom: null
    } : value == SaladBowlType.gm250 ? {
        gm250: null
    } : value == SaladBowlType.gm350 ? {
        gm350: null
    } : value == SaladBowlType.gm500 ? {
        gm500: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
